Fixes issue #1070, Sphinx fails python 2.7
pywbem/pywbemtools pull request #1072
Opened 2021-11-01 20:42 UTC by KSchopmeyer

Fixes an issue where Sphinx fails with python < 3.5 because of an update
to docutils to 0.18. Limited docutils for python 3.5.

We also set some of the Sphinx limits from pywbem dev_requirements.txt.

2021-11-09 18:25 UTC, andy-maier commented on minimum-constraints.txt
> +Sphinx>= 3.5.4; python_version >= '3.5'
This should compare with == not with >=

2021-11-09 18:29 UTC, andy-maier requested changes
see comment

2021-11-09 19:09 UTC, KSchopmeyer commented on minimum-constraints.txt
> +Sphinx>= 3.5.4; python_version >= '3.5'
Fixed. DONE

2021-11-15 20:05 UTC, andy-maier approved these changes

2021-11-16 07:26 UTC, merged