TIP Add security ignores to Makefile
pywbem/pywbemtools pull request #1074
Opened 2021-11-04 19:29 UTC by KSchopmeyer

WIP Added security ignore list similar to pywbem to Makefile

2021-11-09 18:31 UTC, andy-maier approved these changes
Approved, except for the rebase that is needed once the Sphinx PR is merged.

2021-11-17 20:11 UTC, KSchopmeyer commented
Marked review needed only to note that update/rebase done.

2021-11-18 06:49 UTC, andy-maier requested changes
The first commit "Relaxed wrapt pinning to just py27 on windows " has a misleading title, since it also adds security ignores. It seems that the two commits should be squashed into a single one.

2021-11-23 17:56 UTC, andy-maier approved these changes

2021-11-29 06:57 UTC, merged