Ks/test doc bullets list
pywbem/pywbemtools pull request #1220
Opened 2022-10-21 21:44 UTC by KSchopmeyer

Test Only. DO not merge to master

2022-10-22 03:04 UTC, andy-maier requested changes
This PR contains two changes: The fix for the bullets in one commit, and general docs improvements in another commit. I think these commits should ideally be in separate PRs, and the commit with the bullet fix should undo the change to the test envs.

2022-10-22 03:04 UTC, andy-maier commented on rtd-requirements.txt
> +docutils>=0.13.1,<0.17;; python_version >= '3.5'
One semicolon too much

2022-10-23 17:16 UTC, KSchopmeyer commented on .github/workflows/test.yml
>        run: |
No0te that this is just a test of our issue with docs.  I wanted to make the work of the pr as limited as possible.  The real goal is just to kick off the rtd build.

2022-10-25 15:24 UTC, andy-maier commented
Superseded by PR #1221 , closing it.

2022-10-25 15:24 UTC, closed without merging