Refactor mock script documentation
pywbem/pywbemtools pull request #1417
Opened 2024-09-09 16:01 UTC by KSchopmeyer

As part of the issue on old-style mock scripts we reviewed the documentation abd ignificantly modified the mock script documentation.

This pr is a set of changes to the documentation for mocking and mock scripts

2024-09-16 14:59 UTC, andy-maier requested changes

2024-09-16 14:59 UTC, andy-maier commented on pywbemtools/pywbemcli/_cmd_connection.py
> +              "That connectionwill be loaded upon pywbemcli startup if no "
Insert space into "connectionwill"

2024-09-16 15:21 UTC, KSchopmeyer commented on pywbemtools/pywbemcli/_cmd_connection.py
> +              "That connectionwill be loaded upon pywbemcli startup if no "
DONE

2024-09-18 03:43 UTC, andy-maier approved these changes

2024-09-18 03:44 UTC, merged