Ks/missing key warning
pywbem/pywbemtools pull request #812
Opened 2020-11-24 19:49 UTC by KSchopmeyer

Fixes two issues. Note that they are in separate commits:

1. Addition of MissingKeyBinding warning to pywbem causes failures in test_classs_cmds.py. Changes the tests as much as possible to avoid the warning

2. Issue from urllib3 via pywbem issue #2532( (see issue #811) temp fix until pywbem 1.1.3 is released. Fitter the warning in two test modules (test_pywbemcli_operations.py and test_pywbem_server.py).  They are marked so that the filter can be removed in the future.

2020-11-25 19:44 UTC, KSchopmeyer commented
I noted that Andy has resolved at least some of these issues in the github actions pr so I can clean this one up once that pr is committed.  Maybe there is nothing left.

2020-11-26 05:17 UTC, andy-maier commented
Karl, this was also done in PR #808 . I think this PR can be closed.

2020-11-26 05:18 UTC, andy-maier requested changes
Karl, this was also done in PR #808 . I think this PR can be closed, but please double check.

2020-11-26 18:55 UTC, KSchopmeyer commented
Closing this PR since the same changes were made in above mentioned PRs

2020-11-26 18:55 UTC, closed without merging